# Generated by Django 3.1.2 on 2020-10-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_time',
            field=models.CharField(default='21:42:00.593388', max_length=1000),
        ),
    ]
