# Generated by Django 3.1.2 on 2020-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201003_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_time',
            field=models.CharField(default='21:46:27.875024', max_length=1000),
        ),
    ]
