# Generated by Django 3.1.2 on 2020-10-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201003_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_time',
            field=models.CharField(default='23:23:05.806543', max_length=1000),
        ),
    ]
