# Generated by Django 3.1.2 on 2020-10-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201003_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_time',
            field=models.CharField(default='00:25:21.444535', max_length=1000),
        ),
    ]
