# Generated by Django 3.1.2 on 2020-10-03 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201004_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='res_category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_link',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_name',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_size',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_thumbnail',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='res_time',
        ),
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 4, 1, 40, 32, 821034)),
        ),
        migrations.AddField(
            model_name='resource',
            name='unique_identifier',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
