# Generated by Django 3.1.2 on 2020-10-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201004_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='time',
            field=models.CharField(default='1601778027.668456', max_length=50),
        ),
    ]
